importScripts(
    "background/00-core.js",
    "background/10-runtime.js",
    "background/20-drafts.js",
    "background/30-emotes.js",
    "background/40-channels.js",
    "background/50-suggestions.js",
    "background/60-resolve.js"
)
